[package]
name = "extinguish_container"
version = "0.1.0"
edition = "2021"

[dependencies]
extinguish_common.workspace = true
serde = { version = "1", features = ["derive"] }
wamr-rust-sdk = { git = "https://github.com/bytecodealliance/wamr-rust-sdk" }
