[package]
name = "pervade_runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "2"
rquickjs = { version = "0.8", features = ["array-buffer", "bindgen"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
