[package]
name = "pervade_common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
wamr-rust-sdk = { git = "https://github.com/bytecodealliance/wamr-rust-sdk" }

[dev-dependencies]
serde_json = "1"